services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # optional: remove if you don't need direct access
    volumes:
      - ./backend/content:/app/content
      - ./uploads:/app/uploads
      - ./assets:/app/assets
